blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/Gaurav-Gosain/tuios/discussions
    about: Feel free to drop any questions in the Discussions page
  - name: Report a vulnerability
    url: https://github.com/Gaurav-Gosain/tuios/security/policy
    about: Learn more about safely reporting security vulnerabilities
